### ISSUE TITLE
Debian Linux Kernel 5.10, python3.9 not working

### ISSUE THREAD

**Issue by bouillon** [sibradzic/upp#19]
Not working for me with 
XFX AMD RX 6800 XT.
Driver: amdgpu-pro-20.45-1188099-ubuntu-20.04
Debian Linux Kernel 5.10, python3.9
```
upp -p /tmp/custom-pp_table set --write  \
  smc_pptable/SocketPowerLimitAc/0=100   \
  smc_pptable/SocketPowerLimitDc/0=100   \
  smc_pptable/FanStartTemp=100           \
  smc_pptable/FreqTableGfx/1=1550
Traceback (most recent call last):
  File "/usr/local/bin/upp", line 33, in <module>
    sys.exit(load_entry_point('upp==0.0.9', 'console_scripts', 'upp')())
  File "/usr/local/lib/python3.9/dist-packages/upp-0.0.9-py3.9.egg/upp/upp.py", line 373, in main
  File "/usr/local/lib/python3.9/dist-packages/click-8.0.0a1-py3.9.egg/click/core.py", line 1025, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/click-8.0.0a1-py3.9.egg/click/core.py", line 955, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.9/dist-packages/click-8.0.0a1-py3.9.egg/click/core.py", line 1517, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.9/dist-packages/click-8.0.0a1-py3.9.egg/click/core.py", line 1279, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.9/dist-packages/click-8.0.0a1-py3.9.egg/click/core.py", line 710, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/click-8.0.0a1-py3.9.egg/click/decorators.py", line 18, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/upp-0.0.9-py3.9.egg/upp/upp.py", line 334, in set
  File "/usr/local/lib/python3.9/dist-packages/upp-0.0.9-py3.9.egg/upp/decode.py", line 689, in get_value
  File "/usr/local/lib/python3.9/dist-packages/upp-0.0.9-py3.9.egg/upp/decode.py", line 42, in _read_binary_file
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/custom-pp_table'
```

**Comment by bouillon** [comment]
Also 

`
upp --pp-file=extracted.pp_table extract -r VIDEO.rom
Extracting PP table from 'VIDEO.rom' ROM image...
Traceback (most recent call last):
  File "/usr/local/bin/upp", line 33, in <module>
    sys.exit(load_entry_point('upp==0.0.9', 'console_scripts', 'upp')())
  File "/usr/local/lib/python3.9/dist-packages/upp-0.0.9-py3.9.egg/upp/upp.py", line 373, in main
  File "/usr/local/lib/python3.9/dist-packages/click-8.0.0a1-py3.9.egg/click/core.py", line 1025, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/click-8.0.0a1-py3.9.egg/click/core.py", line 955, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.9/dist-packages/click-8.0.0a1-py3.9.egg/click/core.py", line 1517, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.9/dist-packages/click-8.0.0a1-py3.9.egg/click/core.py", line 1279, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.9/dist-packages/click-8.0.0a1-py3.9.egg/click/core.py", line 710, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/click-8.0.0a1-py3.9.egg/click/decorators.py", line 18, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/upp-0.0.9-py3.9.egg/upp/upp.py", line 222, in extract
  File "/usr/local/lib/python3.9/dist-packages/upp-0.0.9-py3.9.egg/upp/decode.py", line 175, in extract_rom
  File "/usr/local/lib/python3.9/dist-packages/upp-0.0.9-py3.9.egg/upp/decode.py", line 89, in _rom_info
  File "/usr/local/lib/python3.9/dist-packages/upp-0.0.9-py3.9.egg/upp/decode.py", line 42, in _read_binary_file
FileNotFoundError: [Errno 2] No such file or directory: 'VIDEO.rom'
`

**Comment by sibradzic** [comment]
Ehmmm, what exactly are you trying to do?

**Comment by bouillon** [comment]
Hi , yes i tried to check if its just working. Ok, it was wrong usage. Everything is working... like

upp -p /sys/class/drm/card0/device/pp_table set --write    smc_pptable/SocketPowerLimitAc/0=100     smc_pptable/SocketPowerLimitDc/0=100     smc_pptable/FanStartTemp=100             smc_pptable/FreqTableGfx/1=1550
Changing smc_pptable.SocketPowerLimitAc.0 from 255 to 100 at 0x32e
Changing smc_pptable.SocketPowerLimitDc.0 from 255 to 100 at 0x33e
Changing smc_pptable.FanStartTemp from 60 to 100 at 0x700
Changing smc_pptable.FreqTableGfx.1 from 2577 to 1550 at 0x530
Commiting changes to '/sys/class/drm/card0/device/pp_table'.
