### ISSUE TITLE
ValueError: Buffer size too small (182 instead of at least 254 bytes)

### ISSUE THREAD

**Issue by NonaSuomy** [sibradzic/upp#31]
Vega FE 

upp --pp-file=/sys/class/drm/card1/device/pp_table dump
Traceback (most recent call last):
  File "/usr/bin/upp", line 8, in <module>
    sys.exit(main())
  File "/usr/lib/python3.10/site-packages/upp/upp.py", line 373, in main
    cli(obj={})()
  File "/usr/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3.10/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/usr/lib/python3.10/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/lib/python3.10/site-packages/upp/upp.py", line 194, in dump
    decode.dump_pp_table(pp_file, rawdump=raw, debug=debug)
  File "/usr/lib/python3.10/site-packages/upp/decode.py", line 665, in dump_pp_table
    data_dict = select_pp_struct(pp_bytes, rawdump, debug)
  File "/usr/lib/python3.10/site-packages/upp/decode.py", line 654, in select_pp_struct
    data_dict = build_data_tree(data, rawbytes, rawdump=rawdump, debug=debug)
  File "/usr/lib/python3.10/site-packages/upp/decode.py", line 569, in build_data_tree
    array_data = c_struct.from_buffer(raw[:top], ofst)
ValueError: Buffer size too small (182 instead of at least 254 bytes)

**Comment by sibradzic** [comment]
Hi @NonaSuomy 

More info please...

Which card is that? I understand it is a secondary card (primary may be an iGPU)? Please share your car's ROM file and/or the content of `/sys/class/drm/card1/device/pp_table dump`.

**Comment by TheGoddessInari** [comment]
The [ROM available here] for instance has the same issue when extracting and dumping the table through upp.

Seeing this on my Vega Frontier Edition ROMs, but not similar ones (like Vega Pro 16GB and and WX9100).

**Comment by NonaSuomy** [comment]
Thank you @TheGoddessInari this information is correct.

**Comment by sibradzic** [comment]
Thanks @TheGoddessInari & @NonaSuomy. I could reproduce your issue with that ROM file, will need to take a deeper look into what's going on here sometime soon...

**Comment by sibradzic** [comment]
@TheGoddessInari, @NonaSuomy, fix released, please check if it works for you.

**Comment by sibradzic** [comment]
@TheGoddessInari, @NonaSuomy, last "fix" resulted in weird `GfxclkDependencyTable`, the true fix needed bit more to it. Please check the latest v0.1.6 release.
