### ISSUE TITLE
Card0 not detected - error 

### ISSUE THREAD

**Issue by Smokolak** [sibradzic/upp#39]
Hi,
I'm trying to use upp dump but getting this:
`Traceback (most recent call last):
  File "/usr/local/bin/upp", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/usr/local/lib/python3.11/site-packages/upp/upp.py", line 387, in main
    cli(obj={})()
    ^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/upp/upp.py", line 208, in dump
    decode.dump_pp_table(pp_file, rawdump=raw, debug=debug)
  File "/usr/local/lib/python3.11/site-packages/upp/decode.py", line 666, in dump_pp_table
    pp_bytes = _read_binary_file(pp_bin_file)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/upp/decode.py", line 42, in _read_binary_file
    f = open(filename, 'rb')
        ^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/sys/class/drm/card0/device/pp_table'
`
Looks like GPU is at card1 and scripts don't detect it?
Fedora 37/38 Radeon 5700XT

**Comment by tictooc** [comment]
Use `--pp-file=` to specify the correct GPU.

If the pp_table is located at card1, then something like below is what you need.
```
upp --pp-file=/sys/class/drm/card1/device/pp_table dump > your_pp_table
```

**Comment by Smokolak** [comment]
Thanks! 
Got one more question, SocketPowerLimitAc & SocketPowerLimitDc for waht stands? I want to raise power limit on my card from 180W default to 210W. Should I change both of them?

**Comment by sibradzic** [comment]
> Should I change both of them?

I think only DC matters with the newer kernels, but I'd change them both if I was you, just to be 200% sure...

**Comment by Smokolak** [comment]
Done for both and it works! Thank You :)
